#
# Apache Camel Salesforce Source
#
apiVersion: sources.knative.dev/v1alpha1
kind: CamelSource
metadata:
  name: camel-salesforce-source
spec:
  source:
    integration:
      configuration:
        - type: configmap
          value: salesforce
        - type: secret
          value: salesforce-secret
    flow:
      from:
        uri: "salesforce:{{salesforce.topic}}"
        parameters:
          notifyForFields: ALL
          updateTopic: true
          notifyForOperationCreate: true
          notifyForOperationUpdate: false
          notifyForOperationDelete: false
          notifyForOperationUndelete: false
          sObjectQuery: SELECT Id, Name, Email, Phone FROM Contact
        steps:
        - to: "log:received?showAll=true&multiline=true"

  sink:
    ref:
      apiVersion: messaging.knative.dev/v1beta1
      kind: InMemoryChannel
      name: salesforce
